### ISSUE TITLE
Out of the box .Net Core 3.1 experience fails

### ISSUE THREAD

**Issue by PrintsCharming** [IdentityManager/IdentityManager2#13]
Following the directions from here: https://www.scottbrady91.com/ASPNET-Identity/IdentityManager2-2020-Update

I get a 404 not found at root.

Cloning the example from here works: https://github.com/scottbrady91/IdentityManager2-Example
until you update the project to ..Net Core 3.1 and update all the packages.

**Comment by scottbrady91** [comment]
Hi! Sorry about the delay. I'm unable to replicate this using the ASP.NET Core 3.1 hosts found in https://github.com/IdentityManager/IdentityManager2/tree/master/src/Hosts. Do you know how your project differs from these?
