### ISSUE TITLE
Logout don't working

### ISSUE THREAD

**Issue by RustamGulamov** [IdentityManager/IdentityManager2#14]
It is my configurations.
` 

            JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Clear();

            services.AddAuthentication()
                .AddCookie("cookie")
                .AddOpenIdConnect("oidc", opt =>
                {
                    opt.Authority = "some-authority";
                    opt.ClientId = "some-id";
                    opt.RequireHttpsMetadata = false;
                    opt.SignInScheme = "cookie";
                });
`
but if click on logout, redirect to remote Identity Server don't working. Now request to the home page is being redirected.

**Comment by RustamGulamov** [comment]
`
services.AddIdentityManager(opt =>
                    opt.SecurityConfiguration =
                        new SecurityConfiguration
                        {
                            HostAuthenticationType = "cookie",
                            HostChallengeType = "oidc",
                            AdditionalSignOutType = "oidc",
                        }).AddIdentityMangerService<AspNetCoreIdentityManagerService<IdentityUser,string, IdentityRole, string>>();
`

**Comment by jpmetcalf** [comment]
Added pull request #17 to fix this issue.

**Comment by scottbrady91** [comment]
Hi! Thanks for reporting this and sorry about the delay.

 It looks like redirects triggered by the `AdditionalSignOutType` were being ignored. I've fixed this in v1.0.1.
