### ISSUE TITLE
Edit role doesn't display data

### ISSUE THREAD

**Issue by Land3r** [IdentityManager/IdentityManager2#15]
Hello,

I am trying to implement IdentityManager2 for managing ASP.Net Core Identity used by IdentityServer4 on a development environment.
The ASP.Net Core Identity and IdentityServer4 stack is working fine

The IdentityManager2 seems to also be working fine (i can create Users and Roles successfully but cannot seem to edit a role).
![image](https://user-images.githubusercontent.com/22073877/85797086-4661f600-b73b-11ea-9eda-61d91bd99df9.png)

No exception seems to be launched by IdentityManager2.

I am using Microsoft.AspNetCore.Identity.EntityFrameworkCore 3.1.5 with a postgres efcore adapter Npgsql.EntityFrameworkCore.PostgreSQL and IdentityManager2.AspNetIdentity 1.0.0 with ASP.Net Core 3.1

What should i check ?

**Comment by scottbrady91** [comment]
Hi! Sorry about the delay in getting back to you.

Currently, there's nothing to edit on a role using our ASP.NET Identity plugin. Were you looking for role claims?
