### ISSUE TITLE
Add User Role

### ISSUE THREAD

**Issue by ghost** [IdentityManager/IdentityManager2#19]
When a Role gets added to a User the application is inserting into AspNetUserClaims table.  This is accurate, however, the AspNetUserRoles table is not being updated with UserID/RoleID.  This table is required for Role Authorization to work properly.

**Comment by brockallen** [comment]
IIRC, roles are added to the claims table. Can you check so see if it's added there?

**Comment by ghost** [comment]
> IIRC, roles are added to the claims table. Can you check so see if it's added there?

Yes the roles are in the claims table as expected.  When I use Authorization within my application the Role authorization does not work unless the entries are in the AspNetUserRoles table as well.  I'm using the code below with my pages:
`@attribute [Authorize(Policy = Policies.IsCompanyOwner)]`
or 
`<AuthorizeView Roles="Administrator">`

I think I'm starting to understand what is going on.  It "maybe" appears that Microsoft is abandoning the AspNetUserRoles table in exchange for Claims and maybe I need to abandon Roles myself and start using the Policies (checking Claims) instead of the build in Roles logic.  

Thanks for the reply and double thanks for the app!
Scott

**Comment by brockallen** [comment]
This is likely related as well: https://leastprivilege.com/2016/08/21/why-does-my-authorize-attribute-not-work/

**Comment by ghost** [comment]
Thank you for the reply and the knowledge.  I changed a simple configuration and now everything works.  My change was in startup.
Replacing this:
`config.AddPolicy("Administrator", policy => policy.RequireRole("Administrator"));`
with this:
`config.AddPolicy("Administrator", policy => policy.RequireClaim("role", "Administrator"));`

It now appears that my everything is working.  Keep up the great work.
