### ISSUE TITLE
Mixing the IdentityManager2 with existing MVC app

### ISSUE THREAD

**Issue by Jenan** [IdentityManager/IdentityManager2#4]
I've tried to use the IDM2 with my existing MVC app - something like this:

```
            app.Map("/idm", idm => idm.UseIdentityManager());
            app.Map("/app", x =>
            {
                x.UseStaticFiles();
                x.UseMvc(routes =>
                {                   
                    routes.MapRoute(
                        name: "default",
                        template: "{controller=Home}/{action=Index}/{id?}");
                });
            });

```
Unfortunately, `PageController` from IDM2 has default get route set to root path, that rewrites for example HomeController in original mvc app.

Any idea - how to combine existing mvc app with IDM2?

**Comment by leastprivilege** [comment]
This is a fundamential issue with ASP.NET Core - see here

http://dhickey.ie/2018/06/09/aspnet-core-nested-apps/
