### ISSUE TITLE
where are the views to manage user, roles, claims etc

### ISSUE THREAD

**Issue by weedkiller** [IdentityManager/IdentityManager2#6]
Hi, I followed your article here and was looking for the view that manage the user, roles, claims and groups.

Also, there was no explanation around scope, profiles etc

**Comment by scottbrady91** [comment]
Views are currently the same as [IdentityManager1](https://github.com/IdentityManager/IdentityManager2/tree/master/src/IdentityManager2/Assets/Templates) but I'm looking to change this at *some* point in the future.

IdentityManager is for user administration in a dev environment. I'm unsure what you mean by scope & profiles. Maybe IdentityServer configuration? If so, that's not a part of this tool and would be served by [AdminUI](https://www.identityserver.com/products).

Hope that helps.
