### ISSUE TITLE
DryIoc - Can't find matching constructor

### ISSUE THREAD

**Issue by SeriousM** [IdentityManager/IdentityManager2#7]
Hi!

I'm using DryIoc as my DI container backend and got to the problem that the MetaController couldn't be constructed.
I've searched for about 2 hours and found out that the constructor of AspNetCoreIdentityManagerService isn't compatible with DryIoc as it contains a default parameter:
`AspNetCoreIdentityManagerService(
      Microsoft.AspNetCore.Identity.UserManager<TUser> userManager,
      Microsoft.AspNetCore.Identity.RoleManager<TRole> roleManager,
      bool includeAccountProperties = true)`

Just as I added a constructor-selector for this constructor the MetaController was able to be constructed.
I please you to remove the default parameter as DryIoc tries to resolve the type bool which is not registered in the container.

Thanks!

**Comment by scottbrady91** [comment]
I can't say I've heard of Dryloc before, but that sounds like limitation in the that DI library, no? If so, I would recommend sticking with manually stating the constructor you would like it to use, or overriding the AspNetCoreIdentityManagerService class.

Out of curiosity, what's the reason for using this DI container?

**Comment by SeriousM** [comment]
I recently discovered that dryioc is supporting default parameters but I
disabled it by accident.

The reason is that it's blazing fast (almost the fastest) while still
having a broad featureset like container in container support (for unit
testing scenarios) and complex lifetime handling.
The default implementation of Microsoft is very good for simple
applications though.

**Comment by scottbrady91** [comment]
Sounds cool. I'll have to check it out.
