### ISSUE TITLE
Conversion to dotnet core 3

### ISSUE THREAD

**Issue by ChaosEngine** [IdentityManager/IdentityManager2#9]
Will there be any plans to convert this project to aspnet core 3? Specifically to useof endpoint routing (conflicts with MCV defaults from dotnet core 2.X ways)

**Comment by scottbrady91** [comment]
Soon 😀

**Comment by ChaosEngine** [comment]
I already started the process on my side. Not yet fully happy (WIP) but I might also prepare a PR for this :-)

**Comment by scottbrady91** [comment]
Hold fire for the minute. I am updating it now and going through some of the outstanding tickets.

**Comment by scottbrady91** [comment]
Done! And now available on master. I'll release a new version this week.

I'd like to use the endpoint routing with something like `MapIdentityManager`, but for now, it's working. I'll open a separate ticket to track that.

If you get a chance to take a look at it, let me know if everything works as expected.
